src/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ComicBookTracker;
using ComicBookTracker.Models;
using System.Linq.Expressions;

namespace ComicBookTracker.Controllers
{
    public class IssueController : Controller
    {
        private readonly ComicBookTrackerContext _context;

        public IssueController(ComicBookTrackerContext context)
        {
            _context = context;
        }

        // GET: Issue
        public async Task<IActionResult> Index(int? authorId, int? seriesId)
        {
            //            int? authorId = 1;
            //          int? seriesId = 43;


            //
            //IQueryable < Issue > comicBookTrackerContext = _context.Issues
            //   .Where(i => i.AuthorId == authorId && i.SeriesId == seriesId)
            //  .Take(25);
            //                .Where(i => (i.AuthorId == authorId) && (i.SeriesId == seriesId))
            //.Include(i => i.Author).Include(i => i.Publisher).Include(i => i.Series);
            //.Where(i => i.SeriesId == seriesId);

            /*
            if (authorId.HasValue)
            {
                comicBookTrackerContext = comicBookTrackerContext.Where(i => i.AuthorId == authorId);
            }
            if (seriesId.HasValue)
            {
                comicBookTrackerContext = comicBookTrackerContext.Where(i => i.SeriesId == seriesId);
            }
            */

            //comicBookTrackerContext = comicBookTrackerContext.Include(i => i.Author).Include(i => i.Publisher).Include(i => i.Series);




            Expression<Func<Issue, bool>> filterLambda = null;
            int resultsToReturn = 500;
            if (authorId.HasValue)
            {
                if (seriesId.HasValue)
                {
                    filterLambda = (i => (i.AuthorId == authorId) && (i.SeriesId == seriesId));
                }
                else
                {
                    filterLambda = (i => i.AuthorId == authorId);
                }
            }
            else
            {
                if (seriesId.HasValue)
                {
                    filterLambda = (i => i.SeriesId == seriesId);
                }
                else
                {
                    filterLambda = (i => true);
                    resultsToReturn = 10;
                }
            }

            // The problem  is that the author sometimes isn't explicit in the DB    AAAAARGH




            var query = _context.Issues
                //.Where(i => (i.AuthorId == authorId) && (i.SeriesId == seriesId))
                //.Where(i => i.Series.AuthorId == authorId)
                .Where(filterLambda)
                .Take(resultsToReturn)
                .Include(i => i.Author)
                .Include(i => i.Series);
    
            string queryString = query.ToQueryString();
            Console.WriteLine(queryString);

            var issueList = await query.ToListAsync();

            return View(issueList);
           //return View(await comicBookTrackerContext.ToListAsync());

        }

        public async Task<IActionResult> Wantlist()
        {
            ViewData["WishList"] = true;
            IQueryable<Issue> query = WantedIssueQuery(recent: false);
            return View(await query.ToListAsync());
        }

        public async Task<IActionResult> PickList()
        {
            ViewData["WishList"] = true;
            IQueryable<Issue> query = WantedIssueQuery(recent: true);
            return View(await query.ToListAsync());
        }


        private IQueryable<Issue> WantedIssueQuery(bool recent)
        { 
            DateTime now = DateTime.Now;
            TimeSpan threeMonths = new TimeSpan(90, 0, 0, 0);
            float currentMonth = now.Year + now.Month / 12;
            float threeMonthsAgo = currentMonth - (3 / 12);

            IQueryable<Issue> query = _context.Issues
                .Where(i => !i.Own && i.Want && !i.MightOwn && !i.MagazineSize);
            if (recent)
            {
                    query = query.Where(i => (i.ReleaseYear + i.ReleaseMonth / 12) >= threeMonthsAgo);

            }
            else
            {
                query = query.Where(i => (i.ReleaseYear + i.ReleaseMonth / 12) < threeMonthsAgo);
            }

            query = query.Include(i => i.Author)
                .Include(i => i.Publisher)
                .Include(i => i.Series);

            return query;
        }

        // GET: Issue/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issue = await _context.Issues
                .Include(i => i.Author)
                .Include(i => i.Publisher)
                .Include(i => i.Series)
                .Include(i => i.Tags)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (issue == null)
            {
                return NotFound();
            }

            return View(issue);
        }

        // GET: Issue/Create
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "Id");
            ViewData["PublisherId"] = new SelectList(_context.Set<Publisher>(), "Id", "Id");
            ViewData["SeriesId"] = new SelectList(_context.Set<Series>(), "Id", "Id");
            return View();
        }

        // POST: Issue/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IssueNumber,Own,ReleaseDay,ReleaseMonth,ReleaseYear,Variant,StoryName,StoryPart,FairPrice,PriceSource,Updated,Created,AuthorId,PublisherId,SeriesId,CoverMonth,CoverYear,Ordered,Want,Annual,ReadingOrder,Special,PullList,MightOwn,MagazineSize")] Issue issue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(issue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "Id", issue.AuthorId);
            ViewData["PublisherId"] = new SelectList(_context.Set<Publisher>(), "Id", "Id", issue.PublisherId);
            ViewData["SeriesId"] = new SelectList(_context.Set<Series>(), "Id", "Id", issue.SeriesId);
            return View(issue);
        }

        // GET: Issue/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issue = await _context.Issues.FindAsync(id);
            if (issue == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "Id", issue.AuthorId);
            ViewData["PublisherId"] = new SelectList(_context.Set<Publisher>(), "Id", "Id", issue.PublisherId);
            ViewData["SeriesId"] = new SelectList(_context.Set<Series>(), "Id", "Id", issue.SeriesId);
            return View(issue);
        }

        // POST: Issue/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,IssueNumber,Own,ReleaseDay,ReleaseMonth,ReleaseYear,Variant,StoryName,StoryPart,FairPrice,PriceSource,Updated,Created,AuthorId,PublisherId,SeriesId,CoverMonth,CoverYear,Ordered,Want,Annual,ReadingOrder,Special,PullList,MightOwn,MagazineSize")] Issue issue)
        {
            if (id != issue.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(issue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IssueExists(issue.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Set<Author>(), "Id", "Id", issue.AuthorId);
            ViewData["PublisherId"] = new SelectList(_context.Set<Publisher>(), "Id", "Id", issue.PublisherId);
            ViewData["SeriesId"] = new SelectList(_context.Set<Series>(), "Id", "Id", issue.SeriesId);
            return View(issue);
        }

        // GET: Issue/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var issue = await _context.Issues
                .Include(i => i.Author)
                .Include(i => i.Publisher)
                .Include(i => i.Series)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (issue == null)
            {
                return NotFound();
            }

            return View(issue);
        }

        // POST: Issue/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)

src/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ComicBookTracker;
using ComicBookTracker.Models;
using ComicBookTracker.Controllers;

namespace ComicBookTracker.Controllers
{
    public class TagController : BaseController
    {

        public TagController(ComicBookTrackerContext context)
            : base(context)
        {            
        }

        // GET: Tag
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tags.ToListAsync());
        }

        // GET: Tag/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .Include(t => t.Issues)
                .ThenInclude(i => i.Series)
                .Include(t => t.Series)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Tag/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tag/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                tag.TimeStampCreate();
                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tag/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FindAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Tag/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name")] Tag tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // TODO: keep the creation timestamp
                tag.TimeStampUpdate();
                try
                {
                    _context.Update(tag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagExists(tag.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Tag/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Tag/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var tag = await _context.Tags.FindAsync(id);
            _context.Tags.Remove(tag);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(long id)
        {
            return _context.Tags.Any(e => e.Id == id);
        }
    }
}

src/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="author" content="michael donnelly">
    <title>@ViewData["Title"] - ComicBookTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />


    <!-- For old IEs -->
    <link rel="shortcut icon" href="~/favicons/favicon.ico" />

    <!-- For new browsers - multisize ico  -->
    <link rel="icon" type="image/x-icon" sizes="16x16 32x32" href="~/favicons/favicon.ico">

    <!-- For iPad with high-resolution Retina display running iOS ≥ 7: -->
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="~/favicons/favicon-152.png">

    <!-- For iPad with high-resolution Retina display running iOS ≤ 6: -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/favicons/favicon-144.png">

    <!-- For iPhone with high-resolution Retina display running iOS ≥ 7: -->
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="~/favicons/favicon-120.png">

    <!-- For iPhone with high-resolution Retina display running iOS ≤ 6: -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/favicons/favicon-114.png">

    <!-- For iPhone 6+ -->
    <link rel="apple-touch-icon-precomposed" sizes="180x180" href="~/favicons/favicon-180.png">

    <!-- For first- and second-generation iPad: -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/favicons/favicon-72.png">

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <link rel="apple-touch-icon-precomposed" href="~/favicons/favicon-57.png">

    <!-- For Old Chrome -->
    <link rel="icon" href="~/favicons/favicon-32.png" sizes="32x32">

    <!-- For IE10 Metro -->
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="favicon-144.png">
    <meta name="theme-color" content="#ffffff">

    <!-- Chrome for Android -->
    <link rel="manifest" href="manifest.json">
    <link rel="icon" sizes="192x192" href="~/favicons/favicon-192.png">


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ComicBookTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Want List</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Issue" asp-action="Wantlist">Back Issues</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Issue" asp-action="PickList">Current</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Series</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Series" asp-action="Index">All</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Series" asp-action="Index" asp-route-currentOnly="true">Current</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tag" asp-action="Index">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trade" asp-action="Index">Trades</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ComicBookTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>